nvmf/rdma_offload: Implement offload fuctionality
Signed-off-by: Sergey Gorenko <sergeygo@nvidia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -142,6 +142,10 @@ function usage() {
 	echo " --with-dpcp=DIR           DPCP library path. Only used with --with-static-xlio."
 	echo " --with-aio-fsdev          Build aio FSDEV component."
 	echo " --without-aio-fsdev       No path required."
+	echo " --with-doca[=DIR]         Build with DOCA. Required for NVMF RDMA Target offload."
+	echo " --without-doca            Path to custom DOCA installation directory may be specified."
+	echo " --with-flexio[=DIR]       Build with FlexIO. Required for nvmf target offload."
+	echo " --without-flexio          Path to custom FLEXIO installation directory may be specified."
 	echo ""
 	echo "Environment variables:"
 	echo ""
@@ -498,6 +502,84 @@ for i in "$@"; do
 		--without-fc)
 			CONFIG[FC]=n
 			CONFIG[FC_PATH]=
+			;;
+		--with-doca=*)
+			doca_path=$(readlink -f ${i#*=})
+			if [ ! -d "$doca_path" ]; then
+				echo "DOCA directory $doca_path not found, aborting"
+				exit 1
+			fi
+
+			doca_incdir=${doca_path}/include
+			if [ ! -d "$doca_incdir" ]; then
+				echo "DOCA incdir $doca_incdir not found, aborting"
+				exit 1
+			fi
+
+			doca_libdir=${doca_path}/lib
+			if [ ! -d "$doca_libdir" ]; then
+				echo "DOCA libdir $doca_libdir not found, aborting"
+				exit 1
+			fi
+			if [ -d "${doca_libdir}/${arch}" ]; then
+				doca_libdir=${doca_libdir}/${arch}
+			fi
+
+			CONFIG[DOCA]=y
+			CFLAGS="${CFLAGS:+$CFLAGS }-DDOCA_ALLOW_EXPERIMENTAL_API -I$doca_incdir"
+			LDFLAGS="${LDFLAGS:+$LDFLAGS }-L$doca_libdir"
+			;;
+		--with-doca)
+			if command -v "pkg-config" > /dev/null 2>&1 && pkg-config --exists doca-common; then
+				CONFIG[DOCA]=y
+				CFLAGS="${CFLAGS:+$CFLAGS }$(pkg-config --cflags doca-common)"
+				LDFLAGS="${LDFLAGS:+$LDFLAGS }$(pkg-config --libs-only-L doca-common)"
+			else
+				echo "doca-common.pc not found, aborting"
+				exit 1
+			fi
+			;;
+		--without-doca)
+			CONFIG[DOCA]=n
+			;;
+		--with-flexio=*)
+			flexio_path=$(readlink -f ${i#*=})
+			if [ ! -d "$flexio_path" ]; then
+				echo "FlexIO directory $flexio_path not found, aborting"
+				exit 1
+			fi
+
+			flexio_incdir=${flexio_path}/include
+			if [ ! -d "$flexio_incdir" ]; then
+				echo "FlexIO incdir $flexio_incdir not found, aborting"
+				exit 1
+			fi
+
+			flexio_libdir=${flexio_path}/lib
+			if [ ! -d "$flexio_libdir" ]; then
+				echo "FlexIO libdir $flexio_libdir not found, aborting"
+				exit 1
+			fi
+			if [ -d "${flexio_libdir}/${arch}" ]; then
+				flexio_libdir=${flexio_libdir}/${arch}
+			fi
+
+			CONFIG[FLEXIO]=y
+			CFLAGS="${CFLAGS:+$CFLAGS }-I$flexio_incdir"
+			LDFLAGS="${LDFLAGS:+$LDFLAGS }-L$flexio_libdir"
+			;;
+		--with-flexio)
+			if command -v "pkg-config" > /dev/null 2>&1 && pkg-config --exists libflexio; then
+				CONFIG[FLEXIO]=y
+				CFLAGS="${CFLAGS:+$CFLAGS }$(pkg-config --cflags libflexio)"
+				LDFLAGS="${LDFLAGS:+$LDFLAGS }$(pkg-config --libs-only-L libflexio)"
+			else
+				echo "libflexio.pc not found, aborting"
+				exit 1
+			fi
+			;;
+		--without-flexio)
+			CONFIG[FLEXIO]=n
 			;;
 		--with-daos)
 			CONFIG[DAOS]=y
