configure: XLIO requires RDMA
xlio uses some rdma utils, linkage fails if rdma is disabled

Change-Id: Ib6341fba484c069e8f779398abf944f80647bd6b
Signed-off-by: Aleksey Marchuk <alexeymar@nvidia.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -976,6 +976,12 @@ if [[ "${CONFIG[FC]}" = "y" ]]; then
 	fi
 fi
 
+if [[ "${CONFIG[XLIO]}" = "y" && "${CONFIG[RDMA]}" = "n" ]]; then
+	echo "ERROR: XLIO requires RDMA to be enabled."
+	echo "Please enable RDMA and re-run this script."
+	exit 1
+fi
+
 function dpdk_version() {
 	# Check DPDK version to determine if mlx5_pci driver is supported
 	local dpdk_ver="none"
